name: Full CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint . || echo "Lint errors found"

    - name: Run Jest tests
      run: npm test || echo "Tests failed"

    - name: Snyk Security Scan
      uses: snyk/actions/node@v1
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Print Node.js version
      run: node -v
